services:
  # Databases
  Doctrine\ORM\EntityManager:
    factory: [ Qm\RealEstate\Shared\Infrastructure\Doctrine\RealEstateEntityManagerFactory, create ]
    arguments:
      - driver: '%env(MORTGAGE_DATABASE_DRIVER)%'
        host: '%env(MORTGAGE_DATABASE_HOST)%'
        port: '%env(MORTGAGE_DATABASE_PORT)%'
        dbname: '%env(MORTGAGE_DATABASE_NAME)%'
        user: '%env(MORTGAGE_DATABASE_USER)%'
        password: '%env(MORTGAGE_DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: Qm.database_connection }
    public: true

